In [3]:
import numpy as np

#N = int(input())
#omega = float(input())
#omega0 = float(input())
#a0 = float(input())

N = 3
omega = 2.0
omega0 = 1.5
a0 = 0.5


matA = np.zeros((N,N))


nc = 0
n = N-1

while nc < N:
    matA[nc][nc] = (omega**2 - omega0**2)
    
    if nc-1 <= 0:
        matA[nc][nc+1] = omega0**2
        
    if nc-1 >= 0 and nc+1 < N:
        matA[nc][nc+1] = omega0**2
        matA[nc][nc-1] = omega0**2
    
    if nc+1 >= N:
        matA[nc][nc-1] = omega0**2 
    nc+=1
    

vecb = [0]*N
vecb[0] = a0
vecb

#Agora que vai começar a putaria 

matA[]

array([[1.75, 2.25, 0.  ],
       [2.25, 1.75, 2.25],
       [0.  , 2.25, 1.75]])

In [19]:
matE

array([[ 1.75      ,  2.25      ,  0.        ],
       [ 0.        , -1.14285714,  2.25      ],
       [ 0.        ,  2.25      ,  1.75      ]])

In [40]:
import numpy as np
def gaussElim(a,b):
    n = len(b)
    # Elimination phase
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                #if not null define λ
                lam = a [i,k]/a[k,k]
                #we calculate the new row of the matrix
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                #we update vector b
                b[i] = b[i] - lam*b[k]
                # backward substitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    
    return b

#initial coefficients
a=np.array([[1.75,2.25,0],[2.25,1.75,2.25],[0,2.25,1.75]])
b=np.array([-0.5,0,0])
aOrig = a.copy() # save original matrix A
bOrig = b.copy() #save original vector b
x = gaussElim(a,b)
#print A transformed for check
print(a)
print("x =\n",x)
#det = np.prod(np.diagonal(a)) #determinant
#print("\ndet =",det)
#check result and numerical precision
print("\nCheck result: [a]{x} - b =\n",np.dot(aOrig,x) - bOrig)

[[ 1.75        2.25        0.        ]
 [ 2.25       -1.14285714  2.25      ]
 [ 0.          2.25        6.1796875 ]]
x =
 [-0.08091024 -0.15929204  0.20480405]

Check result: [a]{x} - b =
 [ 0.00000000e+00  0.00000000e+00 -1.11022302e-16]


In [46]:
from numpy import array, zeros, fabs, linalg

#a = array([[0, 6, -1, 2, 2],
           #[0, 3, 4, 1, 7],
           #[5, 1, 0, 3, -1],
           #[3, 1, 3, 0, 2],
           #[4, 4, 1, -2, 1]], float)
#the b matrix constant terms of the equations 
#b = array([5, 7, 2, 3, 4], float)

#a=np.array([[1.75,2.25,0],[2.25,1.75,2.25],[0,2.25,1.75]])
#b=np.array([0.5,0,0])


om = 2.0
om0 = 1.5
a0 = 0.5


a = np.array([[(om**2-om0**2),om0**2,0.0],[om0**2,(om**2-2*om0**2),om0**2],[0.0,om0**2,(om**2-om0**2)]])
b = [-a0,0.0,0.0]

print("Solution by NumPy:")


print(linalg.solve(a, b))

n = len(b)
x = zeros(n, float)

#first loop specifys the fixed row
for k in range(n-1):
    if fabs(a[k,k]) < 1.0e-12:
        
        for i in range(k+1, n):
            if fabs(a[i,k]) > fabs(a[k,k]):
                a[[k,i]] = a[[i,k]]
                b[[k,i]] = b[[i,k]]
                break

 #applies the elimination below the fixed row

    for i in range(k+1,n):
        if a[i,k] == 0:continue

        factor = a[k,k]/a[i,k]
        for j in range(k,n):
            a[i,j] = a[k,j] - a[i,j]*factor
            #we also calculate the b vector of each row
        b[i] = b[k] - b[i]*factor
print(a)
print(b)


x[n-1] = b[n-1] / a[n-1, n-1]
for i in range(n-2, -1, -1):
    sum_ax = 0
  
    for j in range(i+1, n):
        sum_ax += a[i,j] * x[j]
        
    x[i] = (b[i] - sum_ax) / a[i,i]

print("The solution of the system is:")
print(x)

Solution by NumPy:
[-0.15422078 -0.10227273  0.13149351]
[[ 1.75000000e+00  2.25000000e+00  0.00000000e+00]
 [ 0.00000000e+00  2.63888889e+00 -1.75000000e+00]
 [ 0.00000000e+00  4.44089210e-16 -3.80246914e+00]]
[-0.5, -0.5, -0.5]
The solution of the system is:
[-0.15422078 -0.10227273  0.13149351]


In [44]:

om = 2.0
om0 = 1.5
a0 = 0.5

a = np.array([[(om**2-om0**2),om0**2,0.0],[om0**2,(om**2-2*om0**2),om0**2],[0.0,om0**2,(om**2-om0**2)]])
b = [-a0,0.0,0.0]


In [45]:
a

array([[ 1.75,  2.25,  0.  ],
       [ 2.25, -0.5 ,  2.25],
       [ 0.  ,  2.25,  1.75]])

In [ ]:


##DEEEEEU CERTOOOOOOOO




import numpy as np

N = int(input())
omega = float(input())
omega0 = float(input())
a0 = float(input())

#Tentando criar uma matriz A de tamanho arbitrario NxN com os valores da nossa conta


matA = np.zeros((N,N)) #Definindo uma matriz de zeros para começar


nc = 0 #variaveis auxiliares
n = N-1

while nc < N:
    matA[0][0] = (omega**2 - omega0**2)  #garantindo o primeiro e o ultimo termo que serao sempre os mesmos
    matA[n][n] = (omega**2 - omega0**2)
    
    if nc-1 <= 0:
        matA[nc][nc+1] = omega0**2 #fazendo o primeiro caso da primeira linha para adicionar o termo omega0**2
        
        
    if nc-1 >= 0 and nc+1 < N: #Fazendo todos os casos seguintes menos o ultimo (especial)
        matA[nc][nc+1] = omega0**2
        matA[nc][nc-1] = omega0**2
        matA[nc][nc] = (omega**2 - 2*omega0**2)
    
    if nc+1 >= N:
        matA[nc][nc-1] = omega0**2 #Adicionando o termo omega0**2 no ultimo caso
    nc+=1
    
    
vecb = [0]*N #criando um vetor nulo b de tamanho N 
vecb[0] = -a0 #adicionando o a0 ao vetor


def EliminacaoGaussiana(matA,vecb):
    
    for k in range(0,N-1): #definindo uma variavel auxiliar que começa do 0
        for i in range(k+1,N): #definindo uma variavel auxiliar que começa do 1
            if matA[i,k] != 0.0: #Econtrando todos os casos em que a "escada" do escalonamento não está feita, ou seja em que os temos abaixo da diagonal principal nao sao zeros
                
                m = matA[i,k]/matA[k,k]  #criando os m's que irao servirar para escalonar cada linha
                
                matA[i,k+1:N] = matA[i,k+1:N] - m*matA[k,k+1:N] #subtraindo o valor de cada termo da linha
                
                vecb[i] = vecb[i] - m*vecb[k] #subtraindo também do resultado
                
    for k in range(N-1,-1,-1):
        vecb[k] = (vecb[k] - np.dot(matA[k,k+1:N],vecb[k+1:N]))/matA[k,k] #encontrando o resultado final
    
    return vecb


x = gaussElim(matA,vecb)

dvec =np.copy(x)

for num in dvec:
    print("{:8.4f}".format(num))




In [48]:
g = [0]*3

len(g)

3

In [50]:
matA

array([[ 1.75      ,  2.25      ,  0.        ],
       [ 2.25      , -3.39285714,  2.25      ],
       [ 0.        ,  2.25      ,  3.24210526]])

In [52]:
matA[2,0]

0.0